// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKlLAkvFbcEC6I21Dg1QSHlnNZoHrKc4g',
    appId: '1:243015668806:web:60aece3d9928e9470f6647',
    messagingSenderId: '243015668806',
    projectId: 'flutterbackendapplication',
    authDomain: 'flutterbackendapplication.firebaseapp.com',
    storageBucket: 'flutterbackendapplication.appspot.com',
    measurementId: 'G-WT5P7N506Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKABQPZ1drNuauexkj3nYOddkkTDhmTSE',
    appId: '1:243015668806:android:9cbf3e02233de2300f6647',
    messagingSenderId: '243015668806',
    projectId: 'flutterbackendapplication',
    storageBucket: 'flutterbackendapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjE5P2VK74O0dG1axdiwWTLKjr7DntW_k',
    appId: '1:243015668806:ios:83765791fc977b2b0f6647',
    messagingSenderId: '243015668806',
    projectId: 'flutterbackendapplication',
    storageBucket: 'flutterbackendapplication.appspot.com',
    iosBundleId: 'com.example.learnigDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjE5P2VK74O0dG1axdiwWTLKjr7DntW_k',
    appId: '1:243015668806:ios:d9664ca358632d1f0f6647',
    messagingSenderId: '243015668806',
    projectId: 'flutterbackendapplication',
    storageBucket: 'flutterbackendapplication.appspot.com',
    iosBundleId: 'com.example.learnigDart.RunnerTests',
  );
}
